apiVersion: v1
kind: Service
metadata:
  name: fileconverter-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-30007-30007
      port: 30007
      protocol: TCP
      targetPort: 30007
  selector:
    app: fileconverter
  type: ClusterIP
