apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-gateway
  name: ai-gateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-9092
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: tcp-18888
      port: 18888
      protocol: TCP
      targetPort: 18888
  selector:
    app: ai-gateway
  sessionAffinity: None
  type: ClusterIP
