tad:
  type: helm
  images:
    bot-retrieval-server:
      url: "ccr.ccs.tencentyun.com/tke-market/kb-retrieval:88_2602101802_release_private_v3.2.4_bbf1315a_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}

vector_doc:
  embedding_batch_size: 6 # 文档切片入库，embedding的并发数配置
  image_embedding_batch_size: 5 # 文档切片入库，图片embedding的并发数配置
  batch_add_vector_size: 10 # 批量添加向量的数量
  publish:
    embedding_batch_size: 6 # 文档切片入库，embedding的并发数配置
    image_embedding_batch_size: 5 # 发布时图片embedding的并发数配置
    batch_add_vector_size: 10 # 批量添加向量的数量

retrieval_config:
  vector_recall_enable: true
  text2sql_model_name: nl2sql-16b
imagePullSecretName: qcloudregistrykey
