apiVersion: v1
appVersion: master
description: MinIO is a high performance data infrastructure for machine learning,
  analytics and application data workloads.
home: https://min.io
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/f936ea95-dc39-4b02-87d7-5fb4f1062600.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: Minio
- email: hello@acale.ph
  name: Acaleph
name: minio
sources:
- https://github.com/minio/minio
version: 5.0.6
