apiVersion: v1
kind: Service
metadata:
  labels:
    app: finance
  name: finance
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-9091
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: finance
  type: ClusterIP
