tad:
  type: helm
  namespace: ti-base
  registries:
    images: registry.tce.com
    packages: registry.tce.com:1181
  images:
    ti-ingress-controller:
      url: ccr.ccs.tencentyun.com/tke-market/ti-ingress-controller:feature_3.9-lke_7695473b_20260120_zhiyan31

# 服务本身部署的命名空间
namespace: ti-base

# 拉取镜像需要使用的密钥名称
imagePullSecretName: qcloudregistrykey
