apiVersion: v1
kind: Service
metadata:
  labels:
    app: vector-db-manager
  name: vector-db-manager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-10001
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: tcp-18888
      port: 18888
      protocol: TCP
      targetPort: 18888
    - name: tcp-10003
      port: 10003
      protocol: TCP
      targetPort: 10003
  selector:
    app: vector-db-manager
  type: ClusterIP
