# Default values for mpi-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ccr.ccs.tencentyun.com/kubeflow-oteam/elastic-jupyter-operator
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.1"

namespace: 
  create: true
  name: "enterprise-gateway"

nameOverride: ""
fullnameOverride: ""