apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-manager-controllers
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llm-manager-controllers
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llm-manager-controllers-role
subjects:
  - kind: ServiceAccount
    name: llm-manager-controllers
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: llm-manager-controllers
  apiGroup: rbac.authorization.k8s.io
