apiVersion: v1
appVersion: 2.2.1
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/84303761-3ea2-4cf9-908f-01f39166c24c.png
keywords:
- traefik
- ingress
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ludovic@containo.us
  name: ldez
name: traefik
sources:
- https://github.com/containous/traefik
version: 8.9.0
