apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-parser-server
  name: web-parser-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-10001
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: tcp-18888
      port: 18888
      protocol: TCP
      targetPort: 18888
  selector:
    app: web-parser-server
  sessionAffinity: None
  type: ClusterIP
