apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-30009-30009
      port: 30009
      protocol: TCP
      targetPort: 30009
  selector:
    app: crawler
  type: ClusterIP
