tad:
  type: helm
  images:
    agent-config-server:
      url: "ccr.ccs.tencentyun.com/tke-market/agent-config-server:37_2512022147_release_private_v3.2.4_5eabc54f_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
agentconfigserver:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
imagePullSecretName: qcloudregistrykey
