{{- if eq (include "needInitContainer" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adp-pod-reader-binding
  labels:
    {{- include "adp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: adp-pod-reader
subjects:
  - kind: ServiceAccount
    name: adp-reader
    namespace: {{ .Release.Namespace }}
{{- end }}
