{{- if eq (include "needInitContainer" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: adp-pod-reader
  labels:
    {{- include "adp.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
