appVersion: 6.5.2
description: Kibana
home: https://github.com/elastic/helm-charts
maintainers:
- email: michael.russell@elastic.co
  name: Michael Russell
name: kibana
sources:
- https://github.com/elastic/kibana
version: 6.5.2-alpha1
