apiVersion: v1
kind: Service
metadata:
  labels:
    app: botknowledgeconfigserver
  name: botknowledgeconfigserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: botknowledgeconfigserver-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: botknowledgeconfigserver-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: botknowledgeconfigserver-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: botknowledgeconfigserver-9092
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: botknowledgeconfigserver
  sessionAffinity: None
  type: ClusterIP