apiVersion: v1
appVersion: 11.8.0
description: Chart for PostgreSQL, an object-relational database management system
  (ORDBMS) with an emphasis on extensibility and on standards-compliance.
engine: gotpl
home: https://www.postgresql.org/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/d162ed18-b7a3-4b74-ba3e-ab5c99c71b08.png
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
maintainers:
- email: containers@bitnami.com
  name: Bitnami
- email: cedric@desaintmartin.fr
  name: desaintmartin
name: postgresql
sources:
- https://github.com/bitnami/bitnami-docker-postgresql
version: 8.10.14
