{{- if and .Values.defaultBackend.enabled  .Values.defaultBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    component: "{{ .Values.controller.name }}"
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-backend
  name: {{ template "ingress-nginx.defaultBackend.serviceAccountName" . }}
{{- end }}
