apiVersion: v1
kind: Service
metadata:
  labels:
    app: kernel
  name: kernel
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: kernel-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kernel
  sessionAffinity: None
  type: ClusterIP