apiVersion: v1
kind: Service
metadata:
  labels:
    app: markmap-sidecar
  name: markmap-sidecar
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: markmap-sidecar-7001
      port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    app: pluginexecserver
  sessionAffinity: None
  type: ClusterIP