apiVersion: v1
kind: Service
metadata:
  labels:
    app: pluginexecserver
  name: pluginexecserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: pluginexecserver-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: pluginexecserver-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: pluginexecserver-8002
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: pluginexecserver-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: pluginexecserver
  sessionAffinity: None
  type: ClusterIP