apiVersion: v1
kind: Service
metadata:
  labels:
    app: channelproxysvr
  name: channelproxysvr
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
      nodePort: 30080
    - name: tcp-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: tcp-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: channelproxysvr
  sessionAffinity: None
  type: NodePort