# Default values for distributed-jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

master:
  ## The number of pods in the master deployment
  replicaCount: 1
  heap_size: 2g

server:
  ## The number of pods in the server deployment
  replicaCount: 3
  heap_size: 2g

image:
  ## Specify an imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: IfNotPresent

  ## The repository and image
  ## ref: https://hub.docker.com/r/pedrocesarti/jmeter-docker/
  #  repository: "pedrocesarti/jmeter-docker"
  repository: "ccr.ccs.tencentyun.com/jmeter-test/jmeter-helm-docker"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/pedrocesarti/jmeter-docker/tags/
  #  tag: "5.3"
  tag: "v1.1"


