apiVersion: v1
kind: Secret
metadata:
  name: ti-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  RSA_PUBLIC_KEY: {{ $.Values.global.rsa.publicKey | toString | b64enc | quote }}
  RSA_PRIVATE_KEY: {{ $.Values.global.rsa.privateKey | toString | b64enc | quote }}
