apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{.Values.serviceName}}
    app.cpaas.io/name: {{.Values.serviceName}}.{{ .Release.Namespace }}
    project.cpaas.io/name: {{ .Release.Namespace }}
  selfLink: /api/v1/namespaces/{{ .Release.Namespace }}/services/{{.Values.serviceName}}
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: {{.Values.serviceName}}
    app.cpaas.io/name: {{.Values.serviceName}}.{{ .Release.Namespace }}
    project.cpaas.io/name: {{ .Release.Namespace }}
  sessionAffinity: None
  type: ClusterIP
