apiVersion: v2
name: bot-workflow-dm-server
description: A helm chart for bot-workflow-dm-server
type: application

version: 1.0.0

appVersion: 1.0.0
maintainers:
  - name: randalchen
  - name: v_iferen
