tad:
  type: helm
  images:
    code-interpreter-dispatcher:
      url: "ccr.ccs.tencentyun.com/tke-market/code-interpreter-dispatcher:32_2602051741_release_private_v3.2.4_iaas_97c1154f_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
codeinterpreterdispatcher:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi

imagePullSecretName: qcloudregistrykey
