apiVersion: v1
kind: Service
metadata:
  labels:
    app: bottaskconfigserver
  name: bottaskconfigserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: bottaskconfigserver-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: bottaskconfigserver-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: bottaskconfigserver-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: bottaskconfigserver
  sessionAffinity: None
  type: ClusterIP