kind: ConfigMap
apiVersion: v1
metadata:
  name: ti-auth-web-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.TIWEB_CONFIG = {
      TabTitle: '腾讯云智能',
      // 如果需要配置header logo, 配置路径'/portal/config/platform-title-logo.png'，同时修改platform-title-logo.png文件
      HeaderTitle: '/portal/config/platform-title-logo.png',
      //浏览器title icon
      Favicon: '/portal/config/favicon.ico',
        // 登陆页面
    {{- if or (eq .Values.global.productType "lke") (eq .Values.global.productType "lke&ti") }}
        LoginPage: {
            Title: '智能体开发平台',
            SubTitle: '   ',
            Icon: '/portal/config/login-icon-logo.png',
        },
    {{- else if eq .Values.global.productType "ivh" }}
        LoginPage: {
            Title: '腾讯云智能',
            SubTitle: '数智人平台',
            Icon: '/portal/config/login-icon-logo.png',
        },
    {{- else }}
        LoginPage: {
            Title: '智能体开发平台',
            SubTitle: '   ',
            Icon: '/portal/config/login-icon-logo.png',
        },
    {{- end}}
      // 主页参数
      HomePage: {
        Title: '腾讯云智能',
        SubTitle: '腾讯云智能，整合腾讯先进的AI技术，和腾讯云深耕产业互联网的行业经验，提供包括AI算力、AI开发，到AI产品方案，再到数智化转型方法的四级全链条服务。以“服务于人”为核心宗旨，加速助力各行各业实现数智化转型升级。现已在金融、工业、传媒、出行、文旅、教育、政务、地产、零售、泛互联网等30+行业广泛落地，累计服务20万＋客户。',
        Banner: '/portal/config/home-banner-logo.png',
        QRCodeText: '欢迎添加腾讯云智能企业微信客服，了解更多产品信息',
        QRCodeLogo: '/portal/config/ti-web-qrcode-image.png',
        HideQRCode: false,
      },
      Iaas: true,
      HideLicense: true,
      TiExtraParamOne: '',
      TiExtraParamTwo: '',
      // 退出登录后是否使禁用页面surl
      DisabledLogoutSUrl: false,
      keepLoginPageSurl: true,
      LoginSurlPath: '',
      LoginSuccessPath: '{{ .Values.global.scheme }}://{{ .Values.global.clb }}/portal/#/',
      LogoutSuccessPath: '{{ .Values.global.scheme }}://{{ .Values.global.clb }}/portal/#/login',
      SSOLoginPage: {{ .Values.SSOLoginPage }},
      ssoTokenKey: '{{ .Values.ssoTokenKey }}',
      ssoLogoutUrl: '{{ .Values.ssoLogoutUrl }}',
      Password: {{ (.Values.global).weakPasswordList | default list | toJson }},
      // 是否展示License页面
      HideLicense: true,
      HideSecret: false,
    };
