apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-config
  name: app-config
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-9091
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: app-config
  sessionAffinity: None
  type: ClusterIP
