{{- if .Values.enabled -}}{{/* ENABLED */}}
{{- if eq (include "gitlab.ingress.enabled" $) "true" -}}{{/* INGRESS ENABLED */}}
{{- $gitlabHostname := include "gitlab.gitlab.hostname" $ -}}
{{- $tlsSecret := include "webservice.tlsSecret" $ -}}
{{- include "webservice.datamodel.prepare" $ -}}
{{/* BEGIN range deployments */}}
{{- range $.Values.deployments -}}
{{-   if .ingress.path -}}{{/* SET .ingress.path */}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
*/}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "webservice.fullname.withSuffix" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "{{ template "gitlab.ingressclass" $ }}"
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .ingress.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .ingress.proxyConnectTimeout | quote }}
    {{ include "gitlab.certmanager_annotations" $ }}
  {{- range $key, $value := merge .ingress.annotations $.Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ $gitlabHostname }}
      http:
        paths:
          - path: {{ .ingress.path }}
            backend:
              serviceName: {{ template "webservice.fullname.withSuffix" . }}
              servicePort: {{ $.Values.service.workhorseExternalPort }}
          {{- if eq ( .ingress.path | toString ) "/" }}
          - path: /admin/sidekiq
            backend:
              serviceName: {{ template "webservice.fullname.withSuffix" . }}
              servicePort: {{ $.Values.service.externalPort }}
          {{- end }}
  {{- if (and $tlsSecret (eq (include "gitlab.ingress.tls.enabled" $) "true" )) }}
  tls:
    - hosts:
      - {{ $gitlabHostname }}
      secretName: {{ $tlsSecret }}
  {{- else }}
  tls: []
  {{- end }}
{{- end -}}
{{- end -}}{{/* SET .ingress.path */}}
{{- end -}}{{/* INGRESS ENABLED */}}
{{- end -}}{{/* ENABLED */}}