apiVersion: v1
kind: Service
metadata:
  labels:
    app: codeinterpreterdispatcher
  name: codeinterpreterdispatcher
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: codeinterpreterdispatcher-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: codeinterpreterdispatcher-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: codeinterpreterdispatcher-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: codeinterpreterdispatcher
  sessionAffinity: None
  type: ClusterIP