apiVersion: v1
kind: Service
metadata:
  name: pyright-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-30008-30008
      port: 30008
      protocol: TCP
      targetPort: 30008
  selector:
    app: pyright
  type: ClusterIP
