image:
  repository: ccr.ccs.tencentyun.com/nack/dynamo
  pullPolicy: IfNotPresent
  tag: "202504151804"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

modelPVC:
  enable: true
  name: ai-model
  mountPath: /data

configs:
  Frontend:
    served_model_name: neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    endpoint: dynamo.Processor.chat/completions
    port: 8000

  Processor:
    model: /data/neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    block-size: 128
    max-model-len: 3500
    router: round-robin
  
  router:
    model: neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    min-workers: 1

  # x1 process with 4 GPUs generating output tokens (the "decode" phase).
  VllmWorker:
    model: /data/neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
    # Number of tokens in a batch for more efficient chunked transfers to GPUs.
    block-size: 128
    max-model-len: 3500
    max-num-batched-tokens: 3500
    # Enable prefill at different workers.
    remote-prefill: true
    # Disable local prefill so only disaggregated prefill is used.
    conditional-disagg: false
    tensor-parallel-size: 4
    gpu-memory-utilization: 0.95
    disable-log-requests: true
    router: round-robin
    ServiceArgs:
      workers: 1
      resources:
        gpu: 4

  PrefillWorker:
    model: /data/neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
    block-size: 128
    max-model-len: 3500
    max-num-batched-tokens: 3500
    tensor-parallel-size: 1
    gpu-memory-utilization: 0.95
    disable-log-requests: true
    ServiceArgs:
      workers: 4
      resources:
        gpu: 1

prefillConfigs:
  PrefillWorker:
    model: /data/neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
    kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
    block-size: 128
    max-model-len: 3500
    max-num-batched-tokens: 3500
    tensor-parallel-size: 1
    gpu-memory-utilization: 0.95
    disable-log-requests: true
    ServiceArgs:
      workers: 8
      resources:
        gpu: 1
  

graphs:
  frontend.py: |
    from components.frontend import Frontend
    from components.kv_router import Router
    from components.processor import Processor
    from components.worker import VllmWorker
    from components.prefill_worker import PrefillWorker
    Frontend.link(Processor).link(Router).link(VllmWorker).link(PrefillWorker)


rdma:
  enable: true
  # allowed values: "tke-bridge", "tke-route-eni"
  networkMode: "tke-route-eni"
  hostNetwork: true

single:
  enable: false
  metrics:
    enable: true
    port: 9091
    image:
      repository: ccr.ccs.tencentyun.com/nack/dynamo
      pullPolicy: IfNotPresent
      tag: "metrics-202504121542"
  labels: {}
  annotations: {}
    # eks.tke.cloud.tencent.com/root-cbs-size: '512'
    # eks.tke.cloud.tencent.com/use-image-cache: 'auto'
    # eks.tke.cloud.tencent.com/image-cache-disk-size: '128'
  resources:
    requests:
      nvidia.com/gpu: 8
    limits:
      nvidia.com/gpu: 8

multinode:
  enable: true
  replicas: 1
  metrics:
    enable: false
    port: 9091
    image:
      repository: ccr.ccs.tencentyun.com/nack/dynamo
      pullPolicy: IfNotPresent
      tag: "metrics-202504121542"
    serviceMonitor:
      namespace: kube-system
      apiVersion: "monitoring.coreos.com/v1"
      enable: false
      interval: 15s
      honorLabels: false
      additionalLabels: {}
      relabelings: []
  labels: {}
  annotations: {}
    # eks.tke.cloud.tencent.com/root-cbs-size: '512'
    # eks.tke.cloud.tencent.com/use-image-cache: 'auto'
    # eks.tke.cloud.tencent.com/image-cache-disk-size: '128'
  resources:
    requests:
      nvidia.com/gpu: 8
    limits:
      nvidia.com/gpu: 8
  prefill:
    replicas: 2
    resources:
      requests:
        nvidia.com/gpu: 8
      limits:
        nvidia.com/gpu: 8

natsServerOverride: ""
etcdEndpointsOverride: ""

nats:
  enable: true
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 256Gi

etcd:
  enable: true
  replicaCount: 1
  # Explicitly remove authentication
  auth:
    rbac:
      create: false

  readinessProbe:
    enabled: false

  livenessProbe:
    enabled: false

  persistence:
    size: 256Gi
  
  resources:
    requests:
      cpu: 10
      memory: 20Gi
    limits:
      cpu: 10
      memory: 20Gi
