apiVersion: v1
kind: Service
metadata:
  labels:
    app: short-url
  name: short-url
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: short-url
  sessionAffinity: None
  type: ClusterIP
