{{- if .Values.enabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pre-install-check.fullname" . }}
  labels:
    {{- include "pre-install-check.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": {{ .Values.hook.deletePolicy }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pre-install-check.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pre-install-check.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
