{{- if .Values.enabled }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pre-install-check.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pre-install-check.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": {{ .Values.hook.deletePolicy }}
{{- end }}
{{- end }}
