apiVersion: v1
appVersion: v2.12.0-gitlab
description: Stateless, highly scalable application that stores and lets you distribute
  Docker images
home: https://hub.docker.com/_/registry/
icon: https://hub.docker.com/public/images/logos/mini-logo.svg
keywords:
- registry
- container
- docker
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: registry
sources:
- https://github.com/docker/distribution-library-image
- https://gitlab.com/gitlab-org/charts/gitlab/charts/registry
version: 0.5.0
