tad:
  type: helm
  images:
    web-app:
      url: "ccr.ccs.tencentyun.com/tke-market/webappchatbot:204_2602101658_release_private_v3.2.4.1_iaas-3acf07e77-10163439d-d5c60927"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
namespace: customer
imagePullSecretName: qcloudregistrykey
