apiVersion: v1
kind: Service
metadata:
  labels:
    app: botretrievalserver
  name: botretrievalserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-9091
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: botretrievalserver
  sessionAffinity: None
  type: ClusterIP
