appVersion: 6.5.2
description: Elasticsearch
home: https://github.com/elastic/helm-charts
maintainers:
- email: michael.russell@elastic.co
  name: Michael Russell
name: elasticsearch
sources:
- https://github.com/elastic/elasticsearch
version: 6.5.2-alpha1
