# Default values for gitlab-kas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}
global:
  kas:
    enabled: false
  # hosts:
    # kas:
      # name: kas.example.com
  # imagePullPolicy: IfNotPresent
hpa:
  targetAverageValue: 100m
image:
  repository: registry.gitlab.com/gitlab-org/cluster-integration/gitlab-agent/kas
  tag: "v13.7.0"
ingress:
  annotations: {}
  tls: {}
maxReplicas: 10
maxUnavailable: 1
minReplicas: 2
podLabels: {}
resources:
  requests:
    cpu: 100m
    memory: 100M
service:
  externalPort: 8150
  internalPort: 8150
  type: ClusterIP
metrics:
  enabled: true
  port: 8151
  path: /metrics
serviceAccount:
  enabled: false
  create: false
  annotations: {}
# Tolerations for pod scheduling
tolerations: []
workhorse: {}
  # by default, Workhorse is a part of the Webservice Pods / Service
  # scheme: 'http'
  # host: '0.0.0.0'
  # serviceName: 'webservice'
  # port: 8181
# overwrites the default kas config
customConfig: {}

## Allow to overwrite under which User and Group we're running.
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
