{{- if not .Values.tcpExternalConfig}}
{{- if .Values.enabled }}
{{- $port := include "gitlab.shell.port" . | int -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ingress-nginx.tcp-configmap" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  {{ $port }}: "{{ .Release.Namespace }}/{{ template "fullname" . }}:{{ $port }}"
{{- end -}}
{{- end -}}
