apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex
  namespace: {{ .Release.Namespace }}
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
  labels:
    app: apex
    app.kubernetes.io/name: apex
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: apex
      module: apex
  template:
    metadata:
      labels:
        app: apex
        module: apex
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - apex
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      priorityClassName: system-cluster-critical
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
      - name: apex
        command:
        - /usr/bin/docker-entrypoint-tke.sh
        env:
        - name: LOG_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LOG_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: QD_K8S_CHECK_L5
          value: 'true'
        - name: QD_K8S_CHECK_PROCESS_NAME
          value: apex
        - name: QD_K8S_CHECK_PROCESS_COUNT
          value: '1'
        - name: VERSION
          value: '0.0.5'
        image: {{(index .Values.tad.images "apex").url}}
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - '70'
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /etc/kickStart.d/health_check.sh
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        ports:
        - containerPort: 80
          name: apex-0
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /etc/kickStart.d/health_check.sh
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        {{- if eq .Values.global.clusterSize "minimal" }}
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        {{- else if eq .Values.global.clusterSize "standard" }}
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        {{- else }}
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        {{- end }}
        volumeMounts:
        - mountPath: /tmp/replace
          name: dictionary
        - mountPath: /data/log/apex
          name: volume-log
          subPathExpr: $(LOG_POD_NAME)/apex
        - mountPath: /data/log/monitor
          name: volume-log
          subPathExpr: $(LOG_POD_NAME)/monitor
        - mountPath: /data/dc_tc_mock/
          name: dc-tc-conf
        - mountPath: /apex/conf/config.yaml
          name: config
          subPath: config.yaml
        - mountPath: /usr/bin/docker-entrypoint-tke.sh
          name: entrypoint
          subPath: docker-entrypoint-tke.sh
      terminationGracePeriodSeconds: 70
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      volumes:
      {{- include "dependencyChecker.volumes" . | nindent 6 }}
      - configMap:
          name: dictionary
        name: dictionary
      - configMap:
          name: dc-tc-conf
        name: dc-tc-conf
      - hostPath:
          path: /data/ti-platform/log/apex
          type: DirectoryOrCreate
        name: volume-log
      - configMap:
          name: apex-config
        name: config
      - configMap:
          name: apex-entrypoint
          defaultMode: 0755
        name: entrypoint
