apiVersion: v1
kind: Service
metadata:
  name: apex-cmlb-80-0
  namespace: {{ .Release.Namespace }}
  labels:
    app: apex
    app.kubernetes.io/name: apex
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apex
    module: apex
