apiVersion: v1
kind: Service
metadata:
  name: apex-router-cmlb-8083-0
  namespace: {{ .Release.Namespace }}
  labels:
    app: apex-router
    app.kubernetes.io/name: apex-router
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: apex-router
    module: apex
