{{- if not (eq "true" (include "isTKEkubeVendor" .)) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "scheduler.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "scheduler.labels" . | indent 6 }}
  replicas: {{ .Values.scheduler.replicaCount }}
  template:
    metadata:
      labels:
{{ include "scheduler.labels" . | indent 8 }}
    spec:
      serviceAccountName: scheduler-{{ .Release.Name }}
      containers:
        - name: tke-scheduler
          command:
          - kube-scheduler
          - --leader-elect=true
          - --bind-address=0.0.0.0
          - --scheduler-name=tke-scheduler
          - --lock-object-name=tke-scheduler
          - --eks-config-namespace={{ .Release.Namespace }}
          - --port=0
          image: {{ .Values.scheduler.image.ref }}
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          {{- if .Values.scheduler.resources }}
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
          {{- end}}
    {{- if .Values.scheduler.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scheduler.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
