tad:
  type: helm
  namespace: ti-base
  global:
    productType: lke
  registries:
    images: registry.tce.com
    packages: registry.tce.com:1181
  images:
    ti-auth-web:
      url: ccr.ccs.tencentyun.com/tke-market/ti-tiauth-prod-production:release_private-v3.2.4.0_4284df3ea9c427be8b8c5445e8991ad412e5e9f4_292_image

# 环境变量, DEV | TEST | PROD
env: TEST
# 服务本身部署的命名空间
namespace: ti-base
# 拉取镜像需要使用的密钥名称
imagePullSecretName: qcloudregistrykey
SSOLoginPage: false
ssoLogoutUrl: ''
ssoTokenKey: ''
