apiVersion: v2
name: entity-extractor-server-sand-box
description: A helm chart for entity-extractor-server-sand-box
type: application

version: 1.0.0

appVersion: 1.0.0
maintainers:
  - name: v_iferen
