tad:
  type: helm
  images:
    plugin-cos-util:
      url: "ccr.ccs.tencentyun.com/tke-market/plugin-cos-util:20260115_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}

nameOverride: ""
fullnameOverride: ""

plugincosutil:
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 512Mi
  env:
    LKE_COS_SECRET_ID: "cspuser"
    LKE_COS_SECRET_KEY: "MOCK_SECRET_KEY_VALUE"
    LKE_COS_REGION: "ap-guangzhou"
    LKE_COS_BUCKET: "pe-agent"
    LKE_COS_KEY_PREFIX: "code-interpreter/{}/{}"
    LKE_COS_EXPIRE_TIME: "31536000"
    FILE_MAX_UPLOAD_SIZE: "52428800"
    LKE_MINIO_ACCESS_KEY: "cspuser"
    LKE_MINIO_SECRET_KEY: "MOCK_SECRET_KEY_VALUE"
    LKE_MINIO_ENDPOINT: "minio.ti-inf.svc.cluster.local"
    LKE_MINIO_BUCKET: "qbot"
    LKE_MINIO_SECURE: "false"
    LKE_MINIO_EXPIRE_TIME: "604800"
    LKE_MINIO_KEY_PREFIX: "code-interpreter/{}/{}"
    LKE_MINIO_KEY_PREFIX_DIRECT: "code-interpreter{}"
    STORAGE_TYPE: "minio"

imagePullSecretName: qcloudregistrykey
