{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "registry.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: http
    protocol: TCP
    name: {{ .Values.service.name }}
  {{- if (or .Values.metrics.enabled .Values.debug.prometheus.enabled) }}
  - port: {{ .Values.debug.addr.port }}
    targetPort: debug
    protocol: TCP
    name: http-metrics
  {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end -}}
