appVersion: 9.6.9
description: Object-relational database management system (ORDBMS) with an emphasis
  on extensibility and on standards-compliance.
engine: gotpl
home: https://www.postgresql.org/
icon: https://www.postgresql.org/media/img/about/press/elephant.png
keywords:
- postgresql
- postgres
- database
- sql
maintainers:
- name: aputra
name: postgresql
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/postgres
version: 0.15.0
