tad:
  type: helm
  images:
    bot-memory-server:
      url: "ccr.ccs.tencentyun.com/tke-market/bot-memory-server:37_2602072055_release_private_v3.2.4_iaas_27049722_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
botmemoryserver:
  memory_model_name: cs-normal-70b # 记忆模型名称
imagePullSecretName: qcloudregistrykey
