apiVersion: v1
kind: Service
metadata:
  labels:
    app: agentconfigserver
  name: agentconfigserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: agentconfigserver-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: agentconfigserver-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: agentconfigserver-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: agentconfigserver
  sessionAffinity: None
  type: ClusterIP