apiVersion: v1
appVersion: 1.10.12
description: Airflow is a platform to programmatically author, schedule and monitor workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/_images/pin_large.png
keywords:
- workflow
- dag
- airflow
name: airflow
sources:
- https://airflow.apache.org/
version: 7.8.0
