apiVersion: v2
name: resource-schedule-server
description: A helm chart for resource-schedule-server
type: application

version: 1.0.0

appVersion: 1.0.0
maintainers:
  - name: randalchen
  - name: v_iferen
