apiVersion: v2
name: bot-knowledge-config-server
description: A helm chart for bot-knowledge-config-server
type: application

version: 1.0.0

appVersion: 1.0.0
maintainers:
  - name: randalchen
  - name: v_iferen
