apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot-agent-server
  name: bot-agent-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: tcp-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-8002
      port: 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: bot-agent-server
  sessionAffinity: None
  type: ClusterIP
