apiVersion: v1
kind: ConfigMap
metadata:
  name: rainbow-comm
  namespace: {{ .Release.Namespace }}
data:
  # 公共白名单配置项
  scurl.yaml: |
    scurl_whitelist_config:
      gorm_config:
        name: mysql.db_llm_plugin
        target: dsn://{{ .Values.global.components.db.user }}:{{ .Values.global.components.db.password }}@tcp({{ .Values.global.components.db.host }}:{{ .Values.global.components.db.port }})/db_llm_plugin?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local
      reload_second: 5