tad:
  type: helm
  images:
    resource-gallery:
      url: "ccr.ccs.tencentyun.com/tke-market/resource-gallery:50_2601042025_release_private_v3.2.4_614d59c2_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
imagePullSecretName: qcloudregistrykey
