apiVersion: v1
kind: Service
metadata:
  labels:
    app: botdatastatisticsserver
  name: botdatastatisticsserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: botdatastatisticsserver
  sessionAffinity: None
  type: ClusterIP
