apiVersion: v1
appVersion: 5.0.7
description: Open source, advanced key-value store. It is often referred to as a data
  structure server since keys can contain strings, hashes, lists, sets and sorted
  sets.
engine: gotpl
home: http://redis.io/
icon: https://imgcache.qq.com/qcloud/tcloud_dtc/static/Industry_tke/6ed84689-b3c4-4b00-8777-164a017f3bf1.png
keywords:
- redis
- keyvalue
- database
maintainers:
- email: containers@bitnami.com
  name: Bitnami
- email: cedric@desaintmartin.fr
  name: desaintmartin
name: redis
sources:
- https://github.com/bitnami/bitnami-docker-redis
version: 10.3.4
