kind: ConfigMap
apiVersion: v1
metadata:
  name: entity-extractor-server-sand-box
  namespace: {{ .Release.Namespace }}
data:
  EntityExtractorServerSandBox.json: |
    {
      "config":{
          "oldtask":{
              "is_load": true
          },
          "newtask":{
              "is_load": false
          },
          "synonyms":{
              "table_name": "t_synonyms",
              "is_load": true
          }
      }
    }
