apiVersion: v1
kind: Service
metadata:
  labels:
    app: entity-extractor-server-sand-box 
  name: entity-extractor-server-sand-box
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-10001
      port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: entity-extractor-server-sand-box 
  sessionAffinity: None
  type: ClusterIP
