apiVersion: v1
kind: Service
metadata:
  labels:
    app: pluginconfigserver
  name: pluginconfigserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: pluginconfigserver-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: pluginconfigserver-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: pluginconfigserver-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: pluginconfigserver
  sessionAffinity: None
  type: ClusterIP